version: '3'
services:
  db:
    container_name: pollarr-db
    image: mysql:5.7
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pollarr
    volumes:
      - ./utf8.cnf:/etc/mysql/conf.d/custom.cnf